<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LicensingAdmin</RootNamespace>
    <UserSecretsId>509d1d83-45b7-4292-8ecc-050bd4f65d1c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="MudBlazor" Version="7.15.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LicensingCore\LicensingCore.csproj" />
  </ItemGroup>

</Project>
